#!/bin/bash

# Add vars
. ./setup_vars.sh

echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'HOMEBREW'
echo

if command -v brew 2>/dev/null; then
  echo 'Updating Homebrew'
  brew update
else
  if command -v ruby 2>/dev/null; then
    echo 'Installing Homebrew'
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    echo 'Ruby is required. Aborting.'
    exit 1
  fi
fi

echo
echo '---'
echo 'Installing required formulae'
echo
brew tap universal-ctags/universal-ctags # for universal-ctags - remove when is part of Homebrew repository
. ./brew_formulas.sh

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Installing Ruby'
echo
echo 'N' | rbenv install $RUBY_VERSION

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Installing required modules'
echo

echo 'Perl File::Next'
cpan File::Next
echo

echo 'Python pip'
if command -v pip3 2>/dev/null; then
  echo 'Updating pip'
  pip3 install -U pip
else
  echo 'pip not installed. Installing...'
  curl https://bootstrap.pypa.io/get-pip.py
  python3 get-pip.py
  rm get-pip.py
fi
echo

echo 'Python Neovim'
pip3 install neovim --upgrade
echo

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Cloning Neovim modules'
echo

# install vim-pathogen as plugin manager
mkdir -p $VIM_FOLDER/autoload $bundle_folder && \
curl -LSso $VIM_FOLDER/autoload/pathogen.vim https://tpo.pe/pathogen.vim

. ./vim_plugins_setup.sh
cd $SETUP_FOLDER

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Creating config files symlinks'
echo

# list of files to link
config_files='config_files.txt'

while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "Creating link for $line"
    # remove the existing link or file
    rm -f ~/$line
    # create new link
    ln -s $SETUP_FOLDER/$line ~/$line
done < "$config_files"

# Reload the profile with the new options
shell_session_update() { :; }

echo
echo 'All set. Restart your terminal.'
echo
