#!/bin/bash

# Add vars
. ./setup_vars.sh

echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'HOMEBREW'
echo

if command -v brew 2>/dev/null; then
  echo 'Updating Homebrew'
  brew update
else
  if command -v ruby 2>/dev/null; then
    echo 'Installing Homebrew'
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    echo 'Ruby is required. Aborting.'
    exit 1
  fi
fi

echo
echo '---'
echo 'Installing required formulae'
echo
. "${SETUP_FOLDER}/install_update_brew_formulas.sh"

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Installing asdf'
echo
. "${SETUP_FOLDER}/install_update_asdf.sh"

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Installing Ruby'
echo
asdf install ruby $RUBY_VERSION
asdf global ruby $RUBY_VERSION

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Installing required modules'
echo

echo 'Perl File::Next'
cpan File::Next
echo

echo 'Python pip'
if command -v pip3 2>/dev/null; then
  echo 'Updating pip'
  pip3 install -U pip
else
  echo 'pip not installed. Installing...'
  curl https://bootstrap.pypa.io/get-pip.py
  python3 get-pip.py
  rm get-pip.py
fi
echo

echo 'Python Neovim'
pip3 install neovim --upgrade
echo

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Cloning Neovim modules'
echo

# install vim-pathogen as plugin manager
mkdir -p $VIM_FOLDER/autoload $bundle_folder && \
curl -LSso $VIM_FOLDER/autoload/pathogen.vim https://tpo.pe/pathogen.vim

. "${SETUP_FOLDER}/install_update_vim_plugins.sh"
cd $SETUP_FOLDER

# add my favorite colorscheme :)
curl -LSso $VIM_FOLDER/autoload/togglebg.vim https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/autoload/togglebg.vim
curl -LSso $VIM_FOLDER/colors/solarized.vim https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Downloading git-prompt'
echo
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh > ~/.git-prompt.sh

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Cloning z'
. "${SETUP_FOLDER}/install_z.sh"
echo

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Git config'
git config --global init.templatedir '~/.git_template'
echo

echo
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Creating config files symlinks'
echo
. "${SETUP_FOLDER}/link_config_files.sh"
echo

# Reload the profile with the new options
shell_session_update() { :; }

echo
echo 'All set. Restart your terminal.'
echo
